#            __ __  _     ______  ____  ___ ___   ____  ______    ___       _____ ____    ____  __    __  ____
#          |  T  T| T   |      Tl    j|   T   T /    T|      T  /  _]     / ___/|    \  /    T|  T__T  T|    \
#          |  |  || |   |      | |  T | _   _ |Y  o  ||      | /  [_     (   \_ |  o  )Y  o  ||  |  |  ||  _  Y
#          |  |  || l___l_j  l_j |  | |  \_/  ||     |l_j  l_jY    _]     \__  T|   _/ |     ||  |  |  ||  |  |
#          |  :  ||     T |  |   |  | |   |   ||  _  |  |  |  |   [_      /  \ ||  |   |  _  |l  `  '  !|  |  |
#          l     ||     | |  |   j  l |   |   ||  |  |  |  |  |     T     \    ||  |   |  |  | \      / |  |  |
#          \__,_jl_____j l__j  |____jl___j___jl__j__j  l__j  l_____j      \___jl__j   l__j__j  \_/\_/  l__j__j
#

settings:
  prefix: "&7[&2CustomSpawnpoint&7] &f"

  #set your language for plugin based on LANG directory
  language: EN

  #should player be teleported to death spawn if it has bed respawn location?
  deathSpawnWhenBedSpawnIsCreated: true

  #set delay that player have to wait without moving
  delay: 3

permissions:
  commands:
    admin:
      setSpawnpoint: customSpawnpoint.commands.admin.setSpawnpoint
      reload: customSpawnpoint.commands.admin.reload
data:
  spawnpoints:
    firstjoin:
      #is first join spawn enabled
      enable: true
      world: world
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    death:
      #is death spawn enabled
      enable: true
      world: world
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    default:
      #is /spawn command enabled
      enable: true
      world: world
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0