settings:
  prefix: "&7[&2CustomSpawnpoint&7] &f"

  #set your language for plugin based on LANG directory
  language: EN

  #TODO should player be teleported to death spawn if has bed respawn location?
  deathSpawnWhenBedSpawnIsCreated: true

  #set delay that player have to wait without moving
  delay: 3

permissions:
  commands:
    admin:
      setSpawnpoint: customSpawnpoint.commands.admin.setSpawnpoint
      reload: customSpawnpoint.commands.admin.reload
data:
  spawnpoints:
    firstjoin:
      #is first join spawn is enable
      enable: true
      world: world
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    death:
      #is death spawn is enable
      enable: true
      world: world
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    default:
      #is /spawn command is enable
      enable: true
      world: world
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0